### ISSUE TITLE
Inventory Click Event 

### ISSUE THREAD

**Issue by rkzmnk** [Guillaume-Lebegue/IslandUpgrades#50]
### Expected behavior

Should improve the number of hoppers on the island and show correct value in limits

### Observed/Actual behavior

So i have few i guess (bugs?) Let's begin on upgrades: 

In the latest version of Upgrades ([Upgrades-0.3.0-SNAPSHOT-b102.jar])(https://ci.codemc.io/job/BentoBoxWorld/job/Upgrades/lastSuccessfulBuild/artifact/target/Upgrades-0.3.0-SNAPSHOT-b102.jar) something bad is happening, after click on hopper upgrade nothing happen and the console spits out these errors (Pasted below in Steps/models to reproduce section)

I will add that for example, range update works fine.
![2022-11-22_21 33 29](https://user-images.githubusercontent.com/45878496/203415617-5bf41c7d-010f-44da-afd0-63445133db64.png)
![2022-11-22_21 33 39](https://user-images.githubusercontent.com/45878496/203415623-8e7fbc90-9883-4ff2-9eac-35ae77fa5750.png)

I downgraded upgrades version to: [Upgrades-0.2.0-SNAPSHOT-b85.jar](https://ci.codemc.io/job/BentoBoxWorld/job/Upgrades/85/artifact/target/Upgrades-0.2.0-SNAPSHOT-b85.jar)
and everything looks okay but...
![2022-11-22_21 37 08](https://user-images.githubusercontent.com/45878496/203416271-127b128b-72a8-4ca5-a3db-d9b87d648c65.png)
but then i have issue with limits addon (1.19.0) 
so i upgraded the Hopper limits (+1 hopper on island = limit should be 11)  

![2022-11-22_21 39 27](https://user-images.githubusercontent.com/45878496/203416745-83fe3a30-6598-4cd8-8921-8b46eef518b8.png)
But then message on chat gets brain lag
Next step ill get another one hopper upgrade 
![2022-11-22_21 40 57](https://user-images.githubusercontent.com/45878496/203416946-d3e9807d-27ea-427f-86c5-8584cad30edc.png)
And these things happen (Upgraded hopper 2 times so should be 12 actually) 
![2022-11-22_21 41 08](https://user-images.githubusercontent.com/45878496/203417048-1ab40b23-12de-4343-896c-7e7bc8800339.png)
There are no errors in the console with limits. I restarted island and this happens: 

![2022-11-22_21 43 37](https://user-images.githubusercontent.com/45878496/203417509-d1346264-b3ef-4ef1-b9e3-0aeeb4f5d0ce.png)
![2022-11-22_21 43 48](https://user-images.githubusercontent.com/45878496/203417513-3e865622-e67e-42ff-affa-8ff456ed7089.png)

Addons configs are default. I did not change anything. After restart server, created new island and upgraded hopper to max lvl Hopper in /is upgrade disappear and message still say that i can place only 11 hoppers.

![2022-11-22_21 47 31](https://user-images.githubusercontent.com/45878496/203418343-ddb69d22-0b61-41e0-9e3c-9f8086773049.png)

### Steps/models to reproduce

`[21:25:57] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.21.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2653) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'world.bentobox.limits.objects.IslandBlockCount world.bentobox.limits.listeners.BlockLimitsListener.getIsland(world.bentobox.bentobox.database.objects.Island)'
	at world.bentobox.upgrades.upgrades.BlockLimitsUpgrade.doUpgrade(BlockLimitsUpgrade.java:133) ~[?:?]
	at world.bentobox.upgrades.ui.PanelClick.onClick(PanelClick.java:28) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:56) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:54) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 20 more`

### BentoBox version

[21:50:19] [Server thread/INFO]: Running SPIGOT 1.19.
[21:50:19] [Server thread/INFO]: BentoBox version: 1.21.1
[21:50:19] [Server thread/INFO]: Database: JSON
[21:50:19] [Server thread/INFO]: Loaded Game Worlds:
[21:50:19] [Server thread/INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[21:50:19] [Server thread/INFO]: Loaded Addons:
[21:50:19] [Server thread/INFO]: Bank 1.4.0 (ENABLED)
[21:50:19] [Server thread/INFO]: Biomes 2.0.0 (ENABLED)
[21:50:19] [Server thread/INFO]: BSkyBlock 1.16.0 (ENABLED)
[21:50:19] [Server thread/INFO]: Challenges 1.0.0 (ENABLED)
[21:50:19] [Server thread/INFO]: Chat 1.1.4 (ENABLED)
[21:50:19] [Server thread/INFO]: IslandFly 1.9.0 (ENABLED)
[21:50:19] [Server thread/INFO]: Level 2.9.0 (ENABLED)
[21:50:19] [Server thread/INFO]: Limits 1.19.0 (ENABLED)
[21:50:19] [Server thread/INFO]: Upgrades 0.2.0-SNAPSHOT-b85 (ENABLED)
[21:50:19] [Server thread/INFO]: Warps 1.12.0 (ENABLED)

### Plugin list

[21:50:29] [Server thread/INFO]: Plugins (7): SkinsRestorer, ViaVersion, Vault, BentoBox, Essentials, EssentialsSpawn, Multiverse-Core

**Comment by BONNe** [comment]
If I am not mistaken, you need both dev versions of upgrades and limits (1.19.1)
I do not know exact, but i suspect that some errors are because you downgrade upgrades addon.

**Comment by rkzmnk** [comment]
On first ss all Limits are the newest (not from dev) and upgrades are snapshot cause no stable version has been released yet. 
I'll check again when I get home after work

**Comment by rkzmnk** [comment]
Okay I got the Limits snapshot B301 and Upgrades Snapshot B102 and everythings seems good. But if i got max hopper upgrade hopper still disapear from gui (Shouldn't be "Max level reached"?) 
![2022-11-23_16 47 19](https://user-images.githubusercontent.com/45878496/203589795-83f07159-4868-42fa-9be2-800375b88406.png)
![2022-11-23_16 47 26](https://user-images.githubusercontent.com/45878496/203589799-ddd7497b-9350-4730-ac3a-38c1c7f84deb.png)

**Comment by rkzmnk** [comment]
I think i got it. Sorry for wasting time should do it on discord :D
